In [1]:
import pandas as pd

In [17]:
book = pd.read_csv("log.txt", sep=',', error_bad_lines=False, index_col=False, dtype='unicode')

/tmp/ipykernel_425/837786806.py:1: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  book = pd.read_csv("log.txt", sep=',', error_bad_lines=False, index_col=False, dtype='unicode')

In [18]:
book

,sec,count,bid or ask,0 prise,0 size,1 prise,1 size,2 prise,2 size,3 prise,...,324 size,325 prise,325 size,326 prise,326 size,327 prise,327 size,328 prise,328 size,
0,1.719,0,ASK,8.464,50000,8.465,180000,8.466,249000,8.467,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.719,0,BID,8.46,50000,8.459,400000,8.458,50000,8.457,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5.471,1,ASK,8.464,50000,8.465,180000,8.466,249000,8.467,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5.471,1,BID,8.46,50000,8.459,400000,8.458,50000,8.457,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.471,2,ASK,8.464,50000,8.465,180000,8.466,249000,8.467,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72435,38.112,36217,BID,8.479,174360000,8.478,163721000,8.477,242588000,8.476,...,948000,8.089,1000,8.088,74000,8.087,1307000,,NaN,NaN
72436,39.661,36218,ASK,8.404,1034000,8.405,3213000,8.406,8824000,8.407,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72437,39.661,36218,BID,8.479,174360000,8.478,163721000,8.477,242588000,8.476,...,948000,8.089,1000,8.088,74000,8.087,1307000,,NaN,NaN
72438,40.108,36219,ASK,8.404,1034000,8.405,3213000,8.406,8824000,8.407,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72439,40.108,36219,BID,8.479,174360000,8.478,163721000,8.477,242588000,8.476,...,948000,8.089,1000,8.088,74000,8.087,1307000,,NaN,NaN